services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

    networks:
      - mynetwork

  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    networks:
      - mynetwork

  frontend:
    build:
      context: ../ibis-poc-frontend
      dockerfile: Dockerfile
    container_name: angular-frontend-node
    ports:
      - "${PORT_1}:${PORT_2}"
    depends_on:
      - app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

