name: CD Pipeline - Node.js API

on:
  workflow_run:
    workflows: ["CI Pipeline - Node.js API"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into server and clone or pull repo
        run: |
          ssh -o StrictHostKeyChecking=no root@64.225.62.232 << 'EOF'
            cd apps/ibis-node-server

            if [ -d ".git" ]; then
              git pull origin master
            else
              git clone https://github.com/ibis-miguel/ibis-node-server.git .
            fi
          EOF
